---
abstract: 'Manage .css and .js assets in a web application'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  Directory::Scratch: 0
  Test::Memory::Cycle: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.710'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: File-Assets
no_index:
  directory:
    - inc
    - t
recommends:
  CSS::Minifier: 0
  JavaScript::Minifier: 0
requires:
  Carp::Clan: 0
  Class::Data::Inheritable: 0
  Digest: 0
  HTML::Declare: 0
  IO::Scalar: 0
  MIME::Types: 0
  Module::Pluggable: 0
  Object::Tiny: 0
  Path::Resource: 0
  Scalar::Util: 0
  Tie::LLHash: 0
  XML::Tiny: 0
  perl: 5.8.1
version: 0.056
